apiVersion: v2
name: ollama
description: Get up and running with large language models locally.

type: application

version: 1.7.1

appVersion: "0.5.12"

annotations:
  artifacthub.io/category: ai-machine-learning
  artifacthub.io/changes: |
    - kind: fixed
      description: remove xargs from postStart script
      links:
        - name: PR#149
          url: https://github.com/otwld/ollama-helm/pull/149

kubeVersion: "^1.16.0-0"
home: https://ollama.ai/
icon: https://ollama.ai/public/ollama.png
keywords:
  - ai
  - llm
  - llama
  - mistral
sources:
  - https://github.com/ollama/ollama
  - https://github.com/otwld/ollama-helm
maintainers:
  - name: OTWLD
    email: contact@otwld.com
